%% This file is autogenerated ...

%% This file contains virtual vehicle configuration information.

%% This file is saved at time 26-Oct-2025 21:40:10
                     ConfigInfos.Version = '25.2.0.2998904 (R2025b)';
                   ConfigInfos.SessionID = 'Kart.m';
                   ConfigInfos.LicStatus = [1,1,1,1,1,1,1,1,1];
                ConfigInfos.ProjPathText = 'C:\Users\owenc\Documents\VIP';
                    ConfigInfos.ProjPath = 'C:\Users\owenc\Documents\VIP\VirtualVehicle\VirtualVehicle';
                 ConfigInfos.SessionName = 'Kart';
                 ConfigInfos.XmlPathText = 'C:\Users\owenc\Documents\VIP\VVCCustomCatalog.xml';
               ConfigInfos.TemplateModel = 'VirtualVehicleTemplateArchitecture';
          ConfigInfos.TemplatePlantModel = 'SimulinkPlantModelsArchitecture';
                 ConfigInfos.ConfigModel = 'ConfiguredVirtualVehicleModel';
            ConfigInfos.ConfigPlantModel = 'ConfiguredSimulinkPlantModel';
                    ConfigInfos.VehClass = 'Passenger Vehicle';
                     ConfigInfos.VehArct = 'Electric Vehicle 1EM';
                      ConfigInfos.VehDyn = 1;
              ConfigInfos.PlantModelType = 'Simulink';
                  ConfigInfos.VehChassis = 'Vehicle Body 6DOF Longitudinal and Lateral';
%% Vehicle Configuration
ConfigInfos.FeatureVariantSelectedMap=containers.Map;
ConfigInfos.FeatureVariantSelectedMap('Active Differential Control') = 'No Control';
ConfigInfos.FeatureVariantSelectedMap('ActiveDifferentialControl') = 'No Control';
ConfigInfos.FeatureVariantSelectedMap('Axle Interconnect') = 'No Interconnect';
ConfigInfos.FeatureVariantSelectedMap('Battery Management System') = 'Battery Management System';
ConfigInfos.FeatureVariantSelectedMap('Body and Frame') = 'Vehicle Body 6DOF Longitudinal and Lateral';
ConfigInfos.FeatureVariantSelectedMap('Brake Control Unit') = 'Open Loop';
ConfigInfos.FeatureVariantSelectedMap('Brake System') = 'Brake System';
ConfigInfos.FeatureVariantSelectedMap('DC-DC Converter') = 'HVDCPassThrough';
ConfigInfos.FeatureVariantSelectedMap('Drive Shaft Torque Routing') = 'One Actuator FWD';
ConfigInfos.FeatureVariantSelectedMap('Driver') = 'Longitudinal Driver';
ConfigInfos.FeatureVariantSelectedMap('Drivetrain') = 'Rear Wheel Drive';
ConfigInfos.FeatureVariantSelectedMap('Drivetrain Wheel Speed Route') = 'Bus';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 1') = 'Electric Vehicle 1EM - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 2') = 'Electric Vehicle 2EM - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 3') = 'Electric Vehicle 3EM Dual Front - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 4') = 'Electric Vehicle 4EM - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Motors') = '1EM';
ConfigInfos.FeatureVariantSelectedMap('ElectricMachine2') = 'Electric Vehicle 2EM - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('ElectricMachine3') = 'Electric Vehicle 3EM Dual Front - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('ElectricMachine4') = 'Electric Vehicle 4EM - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Energy Storage') = 'Ideal Voltage Source';
ConfigInfos.FeatureVariantSelectedMap('Engine') = 'No Engine';
ConfigInfos.FeatureVariantSelectedMap('Engine Control Unit') = 'No Engine Controller';
ConfigInfos.FeatureVariantSelectedMap('Environment') = 'Ambient Conditions';
ConfigInfos.FeatureVariantSelectedMap('Final Drive') = 'Final Drive';
ConfigInfos.FeatureVariantSelectedMap('Front Axle Compliances') = 'Axle Compliances';
ConfigInfos.FeatureVariantSelectedMap('Front Brake Type') = 'Disc';
ConfigInfos.FeatureVariantSelectedMap('Front Differential System') = 'Open Differential';
ConfigInfos.FeatureVariantSelectedMap('Front Suspension') = 'MacPherson Front Suspension';
ConfigInfos.FeatureVariantSelectedMap('Front Tire Data') = 'MF Tires Longitudinal Front';
ConfigInfos.FeatureVariantSelectedMap('Front Tire and Wheel') = 'MF Tires Longitudinal and Lateral Front';
ConfigInfos.FeatureVariantSelectedMap('FrontTireData') = 'MF Tires Longitudinal Front';
ConfigInfos.FeatureVariantSelectedMap('Hitch') = 'Hitch 3DOF';
ConfigInfos.FeatureVariantSelectedMap('Power Generation') = 'Power Generation';
ConfigInfos.FeatureVariantSelectedMap('Powertrain') = 'Electric Vehicle 1EM';
ConfigInfos.FeatureVariantSelectedMap('Rear Axle Compliances') = 'No Axle Compliances';
ConfigInfos.FeatureVariantSelectedMap('Rear Brake Type') = 'Disc';
ConfigInfos.FeatureVariantSelectedMap('Rear Differential System') = 'Active Differential Rear';
ConfigInfos.FeatureVariantSelectedMap('Rear Suspension') = 'Solid Axle Rear Suspension';
ConfigInfos.FeatureVariantSelectedMap('Rear Tire Data') = 'Light passenger car 205/60R15';
ConfigInfos.FeatureVariantSelectedMap('Rear Tire and Wheel') = 'MF Tires Longitudinal and Lateral Rear';
ConfigInfos.FeatureVariantSelectedMap('Refrigeration Loop') = 'System Level';
ConfigInfos.FeatureVariantSelectedMap('Sensor') = 'IMU Sensor';
ConfigInfos.FeatureVariantSelectedMap('Steering System') = 'Mapped Steering';
ConfigInfos.FeatureVariantSelectedMap('Suspension System') = 'Suspension System';
ConfigInfos.FeatureVariantSelectedMap('Thermal Control Unit') = 'No Thermal Control';
ConfigInfos.FeatureVariantSelectedMap('Thermal System') = 'Constant Temperature';
ConfigInfos.FeatureVariantSelectedMap('ThermalSystem') = 'Constant Temperature';
ConfigInfos.FeatureVariantSelectedMap('Tire and Wheel System') = 'Tire and Wheel System';
ConfigInfos.FeatureVariantSelectedMap('Trailer') = 'No Trailer';
ConfigInfos.FeatureVariantSelectedMap('Trailer Body') = 'Trailer Body 3DOF';
ConfigInfos.FeatureVariantSelectedMap('Trailer Suspension') = 'Z Force Splice 3DOF';
ConfigInfos.FeatureVariantSelectedMap('Trailer Tire') = 'MF Tires Longitudinal and Lateral';
ConfigInfos.FeatureVariantSelectedMap('Transmission') = 'Single-Speed Transmission 1EM';
ConfigInfos.FeatureVariantSelectedMap('Transmission Control Unit') = 'Driver Pass Through';
ConfigInfos.FeatureVariantSelectedMap('Variant Source') = 'One Actuator FWD';
ConfigInfos.FeatureVariantSelectedMap('Vehicle Architecture') = 'Electric Vehicle 1EM';
ConfigInfos.FeatureVariantSelectedMap('Vehicle Control Unit') = 'EV 1EM with BMS';

%% User Modified Data

           ConfigInfos.DataModified{1,1} = 'PlntVehMass';
           ConfigInfos.DataModified{1,2} = '109';
           ConfigInfos.DataModified{1,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{1,4} = 'PlntVehMass';
           ConfigInfos.DataModified{1,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{1,6} = 'Body and Frame';

           ConfigInfos.DataModified{2,1} = 'PlntVehDstCGFrntAxl';
           ConfigInfos.DataModified{2,2} = '0.42799';
           ConfigInfos.DataModified{2,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{2,4} = 'PlntVehDstCGFrntAxl';
           ConfigInfos.DataModified{2,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{2,6} = 'Body and Frame';

           ConfigInfos.DataModified{3,1} = 'PlntVehDstCGRearAxl';
           ConfigInfos.DataModified{3,2} = '1.03505';
           ConfigInfos.DataModified{3,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{3,4} = 'PlntVehDstCGRearAxl';
           ConfigInfos.DataModified{3,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{3,6} = 'Body and Frame';

           ConfigInfos.DataModified{4,1} = 'PlntVehCGHgtAxl';
           ConfigInfos.DataModified{4,2} = '-0.023876';
           ConfigInfos.DataModified{4,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{4,4} = 'PlntVehCGHgtAxl';
           ConfigInfos.DataModified{4,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{4,6} = 'Body and Frame';

           ConfigInfos.DataModified{5,1} = 'PlntVehRollMomentInertia';
           ConfigInfos.DataModified{5,2} = '8.43';
           ConfigInfos.DataModified{5,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{5,4} = 'PlntVehRollMomentInertia';
           ConfigInfos.DataModified{5,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{5,6} = 'Body and Frame';

           ConfigInfos.DataModified{6,1} = 'PlntVehPitchMomentInertia';
           ConfigInfos.DataModified{6,2} = '29';
           ConfigInfos.DataModified{6,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{6,4} = 'PlntVehPitchMomentInertia';
           ConfigInfos.DataModified{6,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{6,6} = 'Body and Frame';

           ConfigInfos.DataModified{7,1} = 'PlntVehYawMomentInertia';
           ConfigInfos.DataModified{7,2} = '36.51';
           ConfigInfos.DataModified{7,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{7,4} = 'PlntVehYawMomentInertia';
           ConfigInfos.DataModified{7,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{7,6} = 'Body and Frame';

           ConfigInfos.DataModified{8,1} = 'PlntVehTrckWdth';
           ConfigInfos.DataModified{8,2} = '[1.38 1.38]';
           ConfigInfos.DataModified{8,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{8,4} = 'PlntVehTrckWdth';
           ConfigInfos.DataModified{8,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{8,6} = 'Body and Frame';

           ConfigInfos.DataModified{9,1} = 'PlntVehAeroFrntArea';
           ConfigInfos.DataModified{9,2} = '0.1695467577';
           ConfigInfos.DataModified{9,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{9,4} = 'PlntVehAeroFrntArea';
           ConfigInfos.DataModified{9,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{9,6} = 'Body and Frame';

          ConfigInfos.DataModified{10,1} = 'PlntVehAeroDragCff';
          ConfigInfos.DataModified{10,2} = '0.3';
          ConfigInfos.DataModified{10,3} = 'PassVeh.sldd';
          ConfigInfos.DataModified{10,4} = 'PlntVehAeroDragCff';
          ConfigInfos.DataModified{10,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
          ConfigInfos.DataModified{10,6} = 'Body and Frame';

          ConfigInfos.DataModified{11,1} = 'PlntSpMSStiffness';
          ConfigInfos.DataModified{11,2} = '99999999999999999999999';
          ConfigInfos.DataModified{11,3} = 'PassVeh.sldd';
          ConfigInfos.DataModified{11,4} = 'PlntSpMSStiffness';
          ConfigInfos.DataModified{11,5} = 'MacPherson Front Suspension';
          ConfigInfos.DataModified{11,6} = 'Front Suspension';

          ConfigInfos.DataModified{12,1} = 'PlntSpMSDamping';
          ConfigInfos.DataModified{12,2} = '99999999999999999999999';
          ConfigInfos.DataModified{12,3} = 'PassVeh.sldd';
          ConfigInfos.DataModified{12,4} = 'PlntSpMSDamping';
          ConfigInfos.DataModified{12,5} = 'MacPherson Front Suspension';
          ConfigInfos.DataModified{12,6} = 'Front Suspension';

          ConfigInfos.DataModified{13,1} = 'PlntSpSAStiffness';
          ConfigInfos.DataModified{13,2} = '99999999999999999999999';
          ConfigInfos.DataModified{13,3} = 'PassVeh.sldd';
          ConfigInfos.DataModified{13,4} = 'PlntSpSAStiffness';
          ConfigInfos.DataModified{13,5} = 'Solid Axle Rear Suspension';
          ConfigInfos.DataModified{13,6} = 'Rear Suspension';

          ConfigInfos.DataModified{14,1} = 'PlntSpSAMaxHeight';
          ConfigInfos.DataModified{14,2} = '0';
          ConfigInfos.DataModified{14,3} = 'PassVeh.sldd';
          ConfigInfos.DataModified{14,4} = 'PlntSpSAMaxHeight';
          ConfigInfos.DataModified{14,5} = 'Solid Axle Rear Suspension';
          ConfigInfos.DataModified{14,6} = 'Rear Suspension';

          ConfigInfos.DataModified{15,1} = 'PlntDiffrntl2Ratio';
          ConfigInfos.DataModified{15,2} = '1';
          ConfigInfos.DataModified{15,3} = 'Drivetrain.sldd';
          ConfigInfos.DataModified{15,4} = 'PlntDiffrntl2Ratio';
          ConfigInfos.DataModified{15,5} = 'Active Differential Rear';
          ConfigInfos.DataModified{15,6} = 'Rear Differential System';

          ConfigInfos.DataModified{16,1} = 'PlntEM1TransEff';
          ConfigInfos.DataModified{16,2} = '1';
          ConfigInfos.DataModified{16,3} = 'Drivetrain.sldd';
          ConfigInfos.DataModified{16,4} = 'PlntEM1TransEff';
          ConfigInfos.DataModified{16,5} = 'Single-Speed Transmission 1EM';
          ConfigInfos.DataModified{16,6} = 'Transmission';

          ConfigInfos.DataModified{17,1} = 'PlntBattIdealVolt';
          ConfigInfos.DataModified{17,2} = '48';
          ConfigInfos.DataModified{17,3} = 'BatteryDCDC.sldd';
          ConfigInfos.DataModified{17,4} = 'PlntBattIdealVolt';
          ConfigInfos.DataModified{17,5} = 'Ideal Voltage Source';
          ConfigInfos.DataModified{17,6} = 'Energy Storage';

          ConfigInfos.DataModified{18,1} = 'PlntSteerGearRatio';
          ConfigInfos.DataModified{18,2} = '1';
          ConfigInfos.DataModified{18,3} = 'PassVeh.sldd';
          ConfigInfos.DataModified{18,4} = 'PlntSteerGearRatio';
          ConfigInfos.DataModified{18,5} = 'Mapped Steering';
          ConfigInfos.DataModified{18,6} = 'Steering System';

          ConfigInfos.DataModified{19,1} = 'PlntSteerRackDispBpt';
          ConfigInfos.DataModified{19,2} = '[-45.00000000 -40.00000000 -35.00000000 -30.00000000 -25.00000000 -20.00000000 -15.00000000 -10.00000000 -7.00000000 -5.00000000 -3.00000000 -1.00000000 0.00000000 1.00000000 3.00000000 5.00000000 7.00000000 10.00000000 15.00000000 20.00000000 25.00000000 30.00000000 35.00000000 40.00000000 45.00000000]';
          ConfigInfos.DataModified{19,3} = 'PassVeh.sldd';
          ConfigInfos.DataModified{19,4} = 'PlntSteerRackDispBpt';
          ConfigInfos.DataModified{19,5} = 'Mapped Steering';
          ConfigInfos.DataModified{19,6} = 'Steering System';

          ConfigInfos.DataModified{20,1} = 'PlntSteerLftWhlAngTbl';
          ConfigInfos.DataModified{20,2} = '[-0.73652894 -0.65100781 -0.56723201 -0.48345620 -0.40317106 -0.32114058 -0.24085544 -0.16057029 -0.11170107 -0.08028515 -0.05235988 -0.01570796 0.00000000 0.01570796 0.05235988 0.08028515 0.12217305 0.17453293 0.23911008 0.31590459 0.39269908 0.46774824 0.54105207 0.61086524 0.67544242]';
          ConfigInfos.DataModified{20,3} = 'PassVeh.sldd';
          ConfigInfos.DataModified{20,4} = 'PlntSteerLftWhlAngTbl';
          ConfigInfos.DataModified{20,5} = 'Mapped Steering';
          ConfigInfos.DataModified{20,6} = 'Steering System';

          ConfigInfos.DataModified{21,1} = 'PlntSteerRghtWhlAngTbl';
          ConfigInfos.DataModified{21,2} = '[-0.54454273 -0.51138147 -0.46251225 -0.41364303 -0.35779250 -0.29670597 -0.22863807 -0.17453293 -0.11030300 -0.07853982 -0.04712389 -0.01570796 0.00000000 0.01570796 0.04886922 0.08028515 0.11344640 0.15707963 0.23911008 0.31415927 0.38397244 0.44854962 0.50789081 0.56025069 0.60911991]';
          ConfigInfos.DataModified{21,3} = 'PassVeh.sldd';
          ConfigInfos.DataModified{21,4} = 'PlntSteerRghtWhlAngTbl';
          ConfigInfos.DataModified{21,5} = 'Mapped Steering';
          ConfigInfos.DataModified{21,6} = 'Steering System';

%% Test Plan
          ConfigInfos.TestPlan{1}.Source = 'Scenario.sldd';
            ConfigInfos.TestPlan{1}.Name = 'Increasing Steer';
           ConfigInfos.TestPlan{1}.Cycle = 'Disabled';
          ConfigInfos.TestPlan{1}.Driver = 'Predictive Driver';
       ConfigInfos.TestPlan{1}.Data{1,1} = 'ScnISHandwheelRate';
       ConfigInfos.TestPlan{1}.Data{1,2} = '13.5';
       ConfigInfos.TestPlan{1}.Data{2,1} = 'ScnISMaxHandwheelAng';
       ConfigInfos.TestPlan{1}.Data{2,2} = '30';
       ConfigInfos.TestPlan{1}.Data{3,1} = 'ScnISSteerHoldTime';
       ConfigInfos.TestPlan{1}.Data{3,2} = '2';
       ConfigInfos.TestPlan{1}.Data{4,1} = 'ScnISMaxLatAccel';
       ConfigInfos.TestPlan{1}.Data{4,2} = '0.6';
       ConfigInfos.TestPlan{1}.Data{5,1} = 'PlntVehInitLongPos';
       ConfigInfos.TestPlan{1}.Data{5,2} = '0';
       ConfigInfos.TestPlan{1}.Data{6,1} = 'PlntVehInitLatPos';
       ConfigInfos.TestPlan{1}.Data{6,2} = '0';
       ConfigInfos.TestPlan{1}.Data{7,1} = 'PlntVehInitVertPos';
       ConfigInfos.TestPlan{1}.Data{7,2} = '0';
       ConfigInfos.TestPlan{1}.Data{8,1} = 'PlntVehInitRollAng';
       ConfigInfos.TestPlan{1}.Data{8,2} = '0';
       ConfigInfos.TestPlan{1}.Data{9,1} = 'PlntVehInitPitchAng';
       ConfigInfos.TestPlan{1}.Data{9,2} = '0';
      ConfigInfos.TestPlan{1}.Data{10,1} = 'PlntVehInitYawAng';
      ConfigInfos.TestPlan{1}.Data{10,2} = '0';
      ConfigInfos.TestPlan{1}.Data{11,1} = 'ScnStartTime';
      ConfigInfos.TestPlan{1}.Data{11,2} = '2';
      ConfigInfos.TestPlan{1}.Data{12,1} = 'ScnLongVelRef';
      ConfigInfos.TestPlan{1}.Data{12,2} = '50';
      ConfigInfos.TestPlan{1}.Data{13,1} = 'ScnLongVelUnit';
      ConfigInfos.TestPlan{1}.Data{13,2} = 'mph';
      ConfigInfos.TestPlan{1}.Data{14,1} = 'ScnSteerDir';
      ConfigInfos.TestPlan{1}.Data{14,2} = 'Right';
      ConfigInfos.TestPlan{1}.Data{15,1} = 'ScnSimTime';
      ConfigInfos.TestPlan{1}.Data{15,2} = '60';
      ConfigInfos.TestPlan{1}.Data{16,1} = 'DriverPreviewDist';
      ConfigInfos.TestPlan{1}.Data{16,2} = '6';
      ConfigInfos.TestPlan{1}.Data{17,1} = 'DriverTimeConst';
      ConfigInfos.TestPlan{1}.Data{17,2} = '0.3';
      ConfigInfos.TestPlan{1}.Data{18,1} = 'DriverDrivelineRes';
      ConfigInfos.TestPlan{1}.Data{18,2} = '75';
      ConfigInfos.TestPlan{1}.Data{19,1} = 'DriverRollRes';
      ConfigInfos.TestPlan{1}.Data{19,2} = '800';
      ConfigInfos.TestPlan{1}.Data{20,1} = 'DriverShiftTime';
      ConfigInfos.TestPlan{1}.Data{20,2} = '0.1';
      ConfigInfos.TestPlan{1}.Data{21,1} = 'DriverTractiveForce';
      ConfigInfos.TestPlan{1}.Data{21,2} = '15000';
      ConfigInfos.TestPlan{1}.Data{22,1} = 'DriverFrontCornerStiff';
      ConfigInfos.TestPlan{1}.Data{22,2} = '40000';
      ConfigInfos.TestPlan{1}.Data{23,1} = 'DriverRearCornerStiff';
      ConfigInfos.TestPlan{1}.Data{23,2} = '40000';
      ConfigInfos.TestPlan{1}.Data{24,1} = 'DriverWheelRange';
      ConfigInfos.TestPlan{1}.Data{24,2} = '1.0472';

%% Selected Logging Signals
ConfigInfos.SelectedSignals = {
'Battery.BattInfo.BattSoc',...
'Battery.BattInfo.BattVolt',...
'Battery.BattInfo.BattCurr',...
'Body.BdyFrm.Cg.Vel.xdot',...
'Body.BdyFrm.Cg.Acc.ax',...
'Body.BdyFrm.Cg.Acc.ay',...
'Body.BdyFrm.Cg.Acc.az',...
'Driver.SteerFdbk',...
'Driver.AccelFdbk',...
'Driver.DecelFdbk',...
'Driver.GearFdbk',...
'EM.EMSpd',...
'EM.EMTrq',...
};

%% Finish
