%% This file is autogenerated ...

%% This file contains virtual vehicle configuration information.

%% This file is saved at time 09-Oct-2025 19:02:21
                     ConfigInfos.Version = '25.2.0.2998904 (R2025b)';
                   ConfigInfos.SessionID = 'Kart.m';
                   ConfigInfos.LicStatus = [1,1,1,1,1,1,1,1,1];
                ConfigInfos.ProjPathText = 'C:\Users\owenc\Documents\VIP';
                    ConfigInfos.ProjPath = 'C:\Users\owenc\Documents\VIP\VirtualVehicle\VirtualVehicle';
                 ConfigInfos.SessionName = 'Kart';
                 ConfigInfos.XmlPathText = 'C:\Users\owenc\Documents\VIP\VVCCustomCatalog.xml';
               ConfigInfos.TemplateModel = 'VirtualVehicleTemplateArchitecture';
          ConfigInfos.TemplatePlantModel = 'SimulinkPlantModelsArchitecture';
                 ConfigInfos.ConfigModel = 'ConfiguredVirtualVehicleModel';
            ConfigInfos.ConfigPlantModel = 'ConfiguredSimulinkPlantModel';
                    ConfigInfos.VehClass = 'Passenger Vehicle';
                     ConfigInfos.VehArct = 'Electric Vehicle 1EM';
                      ConfigInfos.VehDyn = 1;
              ConfigInfos.PlantModelType = 'Simulink';
                  ConfigInfos.VehChassis = 'Vehicle Body 6DOF Longitudinal and Lateral';
%% Vehicle Configuration
ConfigInfos.FeatureVariantSelectedMap=containers.Map;
ConfigInfos.FeatureVariantSelectedMap('Active Differential Control') = 'No Control';
ConfigInfos.FeatureVariantSelectedMap('Axle Interconnect') = 'No Interconnect';
ConfigInfos.FeatureVariantSelectedMap('Battery Management System') = 'Battery Management System';
ConfigInfos.FeatureVariantSelectedMap('Body and Frame') = 'Vehicle Body 6DOF Longitudinal and Lateral';
ConfigInfos.FeatureVariantSelectedMap('Brake Control Unit') = 'Open Loop';
ConfigInfos.FeatureVariantSelectedMap('Brake System') = 'Brake System';
ConfigInfos.FeatureVariantSelectedMap('DC-DC Converter') = 'HVDCPassThrough';
ConfigInfos.FeatureVariantSelectedMap('Drive Shaft Torque Routing') = 'One Actuator FWD';
ConfigInfos.FeatureVariantSelectedMap('Driver') = 'Longitudinal Driver';
ConfigInfos.FeatureVariantSelectedMap('Drivetrain') = 'Front Wheel Drive';
ConfigInfos.FeatureVariantSelectedMap('Drivetrain Wheel Speed Route') = 'Bus';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 1') = 'Electric Vehicle 1EM - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 2') = 'Electric Vehicle 2EM - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 3') = 'Electric Vehicle 3EM Dual Front - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 4') = 'Electric Vehicle 4EM - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Motors') = '1EM';
ConfigInfos.FeatureVariantSelectedMap('Energy Storage') = 'Mapped Battery (Electric Vehicle 1EM)';
ConfigInfos.FeatureVariantSelectedMap('Engine') = 'No Engine';
ConfigInfos.FeatureVariantSelectedMap('Engine Control Unit') = 'No Engine Controller';
ConfigInfos.FeatureVariantSelectedMap('Environment') = 'Ambient Conditions';
ConfigInfos.FeatureVariantSelectedMap('Final Drive') = 'Final Drive';
ConfigInfos.FeatureVariantSelectedMap('Front Axle Compliances') = 'Axle Compliances';
ConfigInfos.FeatureVariantSelectedMap('Front Brake Type') = 'Disc';
ConfigInfos.FeatureVariantSelectedMap('Front Differential System') = 'Open Differential';
ConfigInfos.FeatureVariantSelectedMap('Front Suspension') = 'Kinematics and Compliance Independent Suspension Front';
ConfigInfos.FeatureVariantSelectedMap('Front Tire Data') = 'Light passenger car 205/60R15';
ConfigInfos.FeatureVariantSelectedMap('Front Tire and Wheel') = 'MF Tires Longitudinal and Lateral Front';
ConfigInfos.FeatureVariantSelectedMap('Hitch') = 'Hitch 3DOF';
ConfigInfos.FeatureVariantSelectedMap('Power Generation') = 'Power Generation';
ConfigInfos.FeatureVariantSelectedMap('Powertrain') = 'Electric Vehicle 1EM';
ConfigInfos.FeatureVariantSelectedMap('Rear Axle Compliances') = 'No Axle Compliances';
ConfigInfos.FeatureVariantSelectedMap('Rear Brake Type') = 'Disc';
ConfigInfos.FeatureVariantSelectedMap('Rear Differential System') = 'No Differential Rear';
ConfigInfos.FeatureVariantSelectedMap('Rear Suspension') = 'Kinematics and Compliance Independent Suspension Rear';
ConfigInfos.FeatureVariantSelectedMap('Rear Tire Data') = 'Light passenger car 205/60R15';
ConfigInfos.FeatureVariantSelectedMap('Rear Tire and Wheel') = 'MF Tires Longitudinal and Lateral Rear';
ConfigInfos.FeatureVariantSelectedMap('Refrigeration Loop') = 'System Level';
ConfigInfos.FeatureVariantSelectedMap('Sensor') = 'IMU Sensor';
ConfigInfos.FeatureVariantSelectedMap('Steering System') = 'Kinematic Steering';
ConfigInfos.FeatureVariantSelectedMap('Suspension System') = 'Suspension System';
ConfigInfos.FeatureVariantSelectedMap('Thermal Control Unit') = 'No Thermal Control';
ConfigInfos.FeatureVariantSelectedMap('Thermal System') = 'Constant Temperature';
ConfigInfos.FeatureVariantSelectedMap('Tire and Wheel System') = 'Tire and Wheel System';
ConfigInfos.FeatureVariantSelectedMap('Trailer') = 'No Trailer';
ConfigInfos.FeatureVariantSelectedMap('Trailer Body') = 'Trailer Body 3DOF';
ConfigInfos.FeatureVariantSelectedMap('Trailer Suspension') = 'Z Force Splice 3DOF';
ConfigInfos.FeatureVariantSelectedMap('Trailer Tire') = 'MF Tires Longitudinal and Lateral';
ConfigInfos.FeatureVariantSelectedMap('Transmission') = 'Single-Speed Transmission 1EM';
ConfigInfos.FeatureVariantSelectedMap('Transmission Control Unit') = 'Driver Pass Through';
ConfigInfos.FeatureVariantSelectedMap('Variant Source') = 'One Actuator FWD';
ConfigInfos.FeatureVariantSelectedMap('Vehicle Architecture') = 'Electric Vehicle 1EM';
ConfigInfos.FeatureVariantSelectedMap('Vehicle Control Unit') = 'EV 1EM with BMS';

%% User Modified Data

           ConfigInfos.DataModified{1,1} = 'PlntVehMass';
           ConfigInfos.DataModified{1,2} = '109';
           ConfigInfos.DataModified{1,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{1,4} = 'PlntVehMass';
           ConfigInfos.DataModified{1,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{1,6} = 'Body and Frame';

           ConfigInfos.DataModified{2,1} = 'PlntVehDstCGFrntAxl';
           ConfigInfos.DataModified{2,2} = '0.42799';
           ConfigInfos.DataModified{2,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{2,4} = 'PlntVehDstCGFrntAxl';
           ConfigInfos.DataModified{2,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{2,6} = 'Body and Frame';

           ConfigInfos.DataModified{3,1} = 'PlntVehDstCGRearAxl';
           ConfigInfos.DataModified{3,2} = '1.03505';
           ConfigInfos.DataModified{3,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{3,4} = 'PlntVehDstCGRearAxl';
           ConfigInfos.DataModified{3,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{3,6} = 'Body and Frame';

           ConfigInfos.DataModified{4,1} = 'PlntVehCGHgtAxl';
           ConfigInfos.DataModified{4,2} = '-0.023876';
           ConfigInfos.DataModified{4,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{4,4} = 'PlntVehCGHgtAxl';
           ConfigInfos.DataModified{4,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{4,6} = 'Body and Frame';

           ConfigInfos.DataModified{5,1} = 'PlntVehRollMomentInertia';
           ConfigInfos.DataModified{5,2} = '8.43';
           ConfigInfos.DataModified{5,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{5,4} = 'PlntVehRollMomentInertia';
           ConfigInfos.DataModified{5,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{5,6} = 'Body and Frame';

           ConfigInfos.DataModified{6,1} = 'PlntVehPitchMomentInertia';
           ConfigInfos.DataModified{6,2} = '29';
           ConfigInfos.DataModified{6,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{6,4} = 'PlntVehPitchMomentInertia';
           ConfigInfos.DataModified{6,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{6,6} = 'Body and Frame';

           ConfigInfos.DataModified{7,1} = 'PlntVehYawMomentInertia';
           ConfigInfos.DataModified{7,2} = '36.51';
           ConfigInfos.DataModified{7,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{7,4} = 'PlntVehYawMomentInertia';
           ConfigInfos.DataModified{7,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{7,6} = 'Body and Frame';

           ConfigInfos.DataModified{8,1} = 'PlntVehTrckWdth';
           ConfigInfos.DataModified{8,2} = '[1.38 1.38]';
           ConfigInfos.DataModified{8,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{8,4} = 'PlntVehTrckWdth';
           ConfigInfos.DataModified{8,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{8,6} = 'Body and Frame';

           ConfigInfos.DataModified{9,1} = 'PlntVehAeroFrntArea';
           ConfigInfos.DataModified{9,2} = '0.1695467577';
           ConfigInfos.DataModified{9,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{9,4} = 'PlntVehAeroFrntArea';
           ConfigInfos.DataModified{9,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{9,6} = 'Body and Frame';

          ConfigInfos.DataModified{10,1} = 'PlntVehAeroDragCff';
          ConfigInfos.DataModified{10,2} = '0.3';
          ConfigInfos.DataModified{10,3} = 'PassVeh.sldd';
          ConfigInfos.DataModified{10,4} = 'PlntVehAeroDragCff';
          ConfigInfos.DataModified{10,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
          ConfigInfos.DataModified{10,6} = 'Body and Frame';

%% Test Plan
          ConfigInfos.TestPlan{1}.Source = 'Scenario.sldd';
            ConfigInfos.TestPlan{1}.Name = 'Increasing Steer';
           ConfigInfos.TestPlan{1}.Cycle = 'Disabled';
          ConfigInfos.TestPlan{1}.Driver = 'Predictive Driver';
       ConfigInfos.TestPlan{1}.Data{1,1} = 'ScnISHandwheelRate';
       ConfigInfos.TestPlan{1}.Data{1,2} = '13.5';
       ConfigInfos.TestPlan{1}.Data{2,1} = 'ScnISMaxHandwheelAng';
       ConfigInfos.TestPlan{1}.Data{2,2} = '30';
       ConfigInfos.TestPlan{1}.Data{3,1} = 'ScnISSteerHoldTime';
       ConfigInfos.TestPlan{1}.Data{3,2} = '2';
       ConfigInfos.TestPlan{1}.Data{4,1} = 'ScnISMaxLatAccel';
       ConfigInfos.TestPlan{1}.Data{4,2} = '0.6';
       ConfigInfos.TestPlan{1}.Data{5,1} = 'PlntVehInitLongPos';
       ConfigInfos.TestPlan{1}.Data{5,2} = '0';
       ConfigInfos.TestPlan{1}.Data{6,1} = 'PlntVehInitLatPos';
       ConfigInfos.TestPlan{1}.Data{6,2} = '0';
       ConfigInfos.TestPlan{1}.Data{7,1} = 'PlntVehInitVertPos';
       ConfigInfos.TestPlan{1}.Data{7,2} = '0';
       ConfigInfos.TestPlan{1}.Data{8,1} = 'PlntVehInitRollAng';
       ConfigInfos.TestPlan{1}.Data{8,2} = '0';
       ConfigInfos.TestPlan{1}.Data{9,1} = 'PlntVehInitPitchAng';
       ConfigInfos.TestPlan{1}.Data{9,2} = '0';
      ConfigInfos.TestPlan{1}.Data{10,1} = 'PlntVehInitYawAng';
      ConfigInfos.TestPlan{1}.Data{10,2} = '0';
      ConfigInfos.TestPlan{1}.Data{11,1} = 'ScnStartTime';
      ConfigInfos.TestPlan{1}.Data{11,2} = '2';
      ConfigInfos.TestPlan{1}.Data{12,1} = 'ScnLongVelRef';
      ConfigInfos.TestPlan{1}.Data{12,2} = '50';
      ConfigInfos.TestPlan{1}.Data{13,1} = 'ScnLongVelUnit';
      ConfigInfos.TestPlan{1}.Data{13,2} = 'mph';
      ConfigInfos.TestPlan{1}.Data{14,1} = 'ScnSteerDir';
      ConfigInfos.TestPlan{1}.Data{14,2} = 'Right';
      ConfigInfos.TestPlan{1}.Data{15,1} = 'ScnSimTime';
      ConfigInfos.TestPlan{1}.Data{15,2} = '60';
      ConfigInfos.TestPlan{1}.Data{16,1} = 'DriverPreviewDist';
      ConfigInfos.TestPlan{1}.Data{16,2} = '6';
      ConfigInfos.TestPlan{1}.Data{17,1} = 'DriverTimeConst';
      ConfigInfos.TestPlan{1}.Data{17,2} = '0.3';
      ConfigInfos.TestPlan{1}.Data{18,1} = 'DriverDrivelineRes';
      ConfigInfos.TestPlan{1}.Data{18,2} = '75';
      ConfigInfos.TestPlan{1}.Data{19,1} = 'DriverRollRes';
      ConfigInfos.TestPlan{1}.Data{19,2} = '800';
      ConfigInfos.TestPlan{1}.Data{20,1} = 'DriverShiftTime';
      ConfigInfos.TestPlan{1}.Data{20,2} = '0.1';
      ConfigInfos.TestPlan{1}.Data{21,1} = 'DriverTractiveForce';
      ConfigInfos.TestPlan{1}.Data{21,2} = '15000';
      ConfigInfos.TestPlan{1}.Data{22,1} = 'DriverFrontCornerStiff';
      ConfigInfos.TestPlan{1}.Data{22,2} = '40000';
      ConfigInfos.TestPlan{1}.Data{23,1} = 'DriverRearCornerStiff';
      ConfigInfos.TestPlan{1}.Data{23,2} = '40000';
      ConfigInfos.TestPlan{1}.Data{24,1} = 'DriverWheelRange';
      ConfigInfos.TestPlan{1}.Data{24,2} = '1.0472';

%% Selected Logging Signals
ConfigInfos.SelectedSignals = {
'Battery.BattInfo.BattSoc',...
'Battery.BattInfo.BattVolt',...
'Battery.BattInfo.BattCurr',...
'Body.BdyFrm.Cg.Vel.xdot',...
'Body.BdyFrm.Cg.Acc.ax',...
'Body.BdyFrm.Cg.Acc.ay',...
'Body.BdyFrm.Cg.Acc.az',...
'Driver.SteerFdbk',...
'Driver.AccelFdbk',...
'Driver.DecelFdbk',...
'Driver.GearFdbk',...
'EM.EMSpd',...
'EM.EMTrq',...
};

%% Finish
